CREATE TABLE IF NOT EXISTS `supinic.com`.`Error` (
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Request_ID` INT(11) UNSIGNED NULL DEFAULT NULL,
	`Type` ENUM('API','View') NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`Message` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`Stack` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`Timestamp` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `FK_Error_Log` (`Request_ID`) USING BTREE,
	CONSTRAINT `FK_Error_Log` FOREIGN KEY (`Request_ID`) REFERENCES `supinic.com`.`Log` (`ID`) ON UPDATE CASCADE ON DELETE SET NULL
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
